services:
  app:
    build: .docker
    volumes:
      - .:/usr/src/app
    command: sleep infinity

  db:
    image: mariadb:10.11
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=neurolabs
    volumes:
      - ./var/mariadb:/var/lib/mysql
